name: 'N-Plus-One Guardian'
description: 'Analisa o código (PHP, TypeScript/Node, Python) em busca de problemas de N+1 queries no banco de dados, alertando no Pull Request.'
author: 'Whentony'
branding:
  icon: 'alert-triangle'
  color: 'red'

inputs:
  github_token:
    description: 'Token de autenticação do GitHub (geralmente secrets.GITHUB_TOKEN)'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
